ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2025 6 11 14 41 39)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright Â© Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMANBOLD"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 700)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "ESP32_Dev_Board_1_N"
    (originalName "ESP32_Dev_Board_1_N")
    (pin (pinNum 1)  (pt -1000 800) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 800) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 800) "EN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 900 800) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 800) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 800) "GPIO23_(VSPI_MOSI)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt -1000 700) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 700) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 700) "GPIO36_(VP)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 900 700) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 700) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 700) "GPIO22_(I2C_SCL)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt -1000 600) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 600) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 600) "GPIO39_(VN)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 900 600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 600) "6" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 600) "GPIO1_(UART0_TX)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt -1000 500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 500) "7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 500) "GPIO34" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 900 500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 500) "8" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 500) "GPIO3_(UART0_RX)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt -1000 400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 400) "9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 400) "GPIO35" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 900 400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 400) "10" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 400) "GPIO21_(I2C_SDA)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt -1000 300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 300) "11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 300) "GPIO32" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 900 300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 300) "12" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 300) "GPIO19_(VSPI_MISO)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt -1000 200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 200) "13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 200) "GPIO33" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 900 200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 200) "14" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 200) "GPIO18_(VPSI_CLK)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt -1000 100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 100) "15" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 100) "GPIO25" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 900 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 100) "16" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 100) "GPIO5_(VSPI_CS0)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt -1000 0) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 0) "17" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 0) "GPIO26" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 900 0) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 0) "18" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 0) "GPIO17_(UART2_TX)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt -1000 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 -100) "19" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 -100) "GPIO27" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 900 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -100) "20" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -100) "GPIO16_(UART2_RX)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 21)  (pt -1000 -200) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 -200) "21" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 -200) "GPIO14_(HSPI_CLK)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 22)  (pt 900 -200) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -200) "22" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -200) "GPIO4" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 23)  (pt -1000 -300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 -300) "23" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 -300) "GPIO12_(HSPI_MISO)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 24)  (pt 900 -300) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -300) "24" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -300) "GPIO2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 25)  (pt -1000 -400) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 -400) "25" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 -400) "GPIO13_(HSPI_MOSI)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 26)  (pt 900 -400) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -400) "26" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -400) "GPIO15_(HSPI_CS0)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 27)  (pt -1000 -500) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 -500) "27" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 -500) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 28)  (pt 900 -500) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -500) "28" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -500) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 29)  (pt -1000 -600) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -1150 -600) "29" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -1000 -600) "VIN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 30)  (pt 900 -600) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1050 -600) "30" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 900 -600) "3V3" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -1000 -700) (pt -1000 900) (width 10) )
    (line (pt -1000 -700) (pt 900 -700) (width 10) )
    (line (pt -1000 900) (pt 900 900) (width 10) )
    (line (pt 900 900) (pt 900 -700) (width 10) )
    (attr "RefDes" ""  (pt -1000 900) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -1000 -800) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "Qwiic_to_I2C_1_N"
    (originalName "Qwiic_to_I2C_1_N")
    (pin (pinNum 1)  (pt 0 -300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -300) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -300) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 0 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 -100) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 -100) "VCC" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 0 100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 100) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 100) "SDA" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 0 300) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -150 300) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 0 300) "SCL" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 0 -400) (pt 0 400) (width 10) )
    (line (pt 0 -400) (pt 400 -400) (width 10) )
    (line (pt 0 400) (pt 400 400) (width 10) )
    (line (pt 400 400) (pt 400 -400) (width 10) )
    (attr "RefDes" ""  (pt 0 400) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 0 -500) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "MLX90640_1_N"
    (originalName "MLX90640_1_N")
    (pin (pinNum 1)  (pt -300 100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 100) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 100) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt -300 -100) (rotation 180.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt -450 -100) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt -300 -100) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 400 100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 550 100) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 400 100) "SDA" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 400 -100) (rotation 0.0) (isFlipped False) (pinLength 300)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 550 -100) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 400 -100) "SCL" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt -300 -300) (pt -300 300) (width 10) )
    (line (pt -300 -300) (pt 400 -300) (width 10) )
    (line (pt -300 300) (pt 400 300) (width 10) )
    (line (pt 400 300) (pt 400 -300) (width 10) )
    (text  (pt -300 -300) "55DEG FOV" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (attr "RefDes" ""  (pt -300 300) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt -300 -500) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
  )
  (symbolDef "3V3_1_N"
    (originalName "3V3_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "PWR" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 100 -100) (pt 100 100) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "GND_1_N"
    (originalName "GND_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 110 100) (pt 110 -100) (width 15) )
    (line (pt 140 70) (pt 140 -70) (width 15) )
    (line (pt 170 40) (pt 170 -40) (width 15) )
    (line (pt 200 10) (pt 200 -10) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (compDef "ESP32_DEV_BOARD"
    (originalName "ESP32_DEV_BOARD")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 30)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (compPin "1" (pinName "EN") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Input) )
    (compPin "2" (pinName "GPIO23_(VSPI_MOSI)") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "3" (pinName "GPIO36_(VP)") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "4" (pinName "GPIO22_(I2C_SCL)") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "5" (pinName "GPIO39_(VN)") (partNum 1) (symPinNum 5) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "6" (pinName "GPIO1_(UART0_TX)") (partNum 1) (symPinNum 6) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "7" (pinName "GPIO34") (partNum 1) (symPinNum 7) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "8" (pinName "GPIO3_(UART0_RX)") (partNum 1) (symPinNum 8) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "9" (pinName "GPIO35") (partNum 1) (symPinNum 9) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "10" (pinName "GPIO21_(I2C_SDA)") (partNum 1) (symPinNum 10) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "11" (pinName "GPIO32") (partNum 1) (symPinNum 11) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "12" (pinName "GPIO19_(VSPI_MISO)") (partNum 1) (symPinNum 12) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "13" (pinName "GPIO33") (partNum 1) (symPinNum 13) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "14" (pinName "GPIO18_(VPSI_CLK)") (partNum 1) (symPinNum 14) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "15" (pinName "GPIO25") (partNum 1) (symPinNum 15) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "16" (pinName "GPIO5_(VSPI_CS0)") (partNum 1) (symPinNum 16) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "17" (pinName "GPIO26") (partNum 1) (symPinNum 17) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "18" (pinName "GPIO17_(UART2_TX)") (partNum 1) (symPinNum 18) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "19" (pinName "GPIO27") (partNum 1) (symPinNum 19) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "20" (pinName "GPIO16_(UART2_RX)") (partNum 1) (symPinNum 20) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "21" (pinName "GPIO14_(HSPI_CLK)") (partNum 1) (symPinNum 21) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "22" (pinName "GPIO4") (partNum 1) (symPinNum 22) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "23" (pinName "GPIO12_(HSPI_MISO)") (partNum 1) (symPinNum 23) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "24" (pinName "GPIO2") (partNum 1) (symPinNum 24) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "25" (pinName "GPIO13_(HSPI_MOSI)") (partNum 1) (symPinNum 25) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "26" (pinName "GPIO15_(HSPI_CS0)") (partNum 1) (symPinNum 26) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "27" (pinName "GND") (partNum 1) (symPinNum 27) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "28" (pinName "GND") (partNum 1) (symPinNum 28) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "29" (pinName "VIN") (partNum 1) (symPinNum 29) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "30" (pinName "3V3") (partNum 1) (symPinNum 30) (gateEq 0) (pinEq 0) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "ESP32_Dev_Board_1_N") )
  )
  (compDef "QWIIC_TO_I2C"
    (originalName "QWIIC_TO_I2C")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 4)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (compPin "1" (pinName "GND") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "2" (pinName "VCC") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "3" (pinName "SDA") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "4" (pinName "SCL") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Passive) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "Qwiic_to_I2C_1_N") )
  )
  (compDef "MLX90640"
    (originalName "MLX90640")
    (compHeader
      (sourceLibrary "")
      (compType Normal)
      (numPins 4)
      (numParts 1)
      (composition Homogeneous)
      (alts (ieeeAlt False) (deMorganAlt False) )
      (refDesPrefix "U")
    )
    (compPin "1" (pinName "VDD") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "2" (pinName "GND") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Passive) )
    (compPin "3" (pinName "SDA") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (compPin "4" (pinName "SCL") (partNum 1) (symPinNum 4) (gateEq 0) (pinEq 0) (pinType Bidirectional) )
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "MLX90640_1_N") )
  )
  (compDef "3V3"
    (originalName "3V3")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "3V3") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "3V3_1_N") )
  )
  (compDef "GND"
    (originalName "GND")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "GND") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "GND_1_N") )
  )
)

(netlist "Netlist_1"
  (compInst "C1"
    (compRef "CAP")
    (originalName "CAP")
    (patternName "CAPC1608X87X35LL15T15")
    (attr "Manufacturer" "Kemet" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Part Number" "C0603C105K3RACTU" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C2"
    (compRef "CAP")
    (originalName "CAP")
    (patternName "CAPC1608X87X35LL15T15")
    (attr "Manufacturer" "Kemet" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Part Number" "C0603C105K3RACTU" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "CAM1"
    (compRef "MLX90640")
    (originalName "MLX90640")
  )
  (compInst "D1"
    (compRef "8706943C75BA83719D021D2FDC8461")
    (originalName "8706943c75ba83719d021d2fdc8461")
    (patternName "FP-HSMS-C170-MFG")
    (attr "Case Code (Imperial)" "0805" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Case Code (Metric)" "2012" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Case/Package" "0805" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Color" "Red" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Depth" "1.25mm" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Dominant Wavelength" "626nm" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Forward Current" "20mA" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Forward Voltage" "2.1V" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "0.8mm" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Illumination Color" "Red" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Lead Free" "Lead Free" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Length" "2mm" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Lens Color" "White" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Lens Style" "Diffused" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Lens Transparency" "Diffused" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Luminous Intensity" "10mcd" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Max Operating Temp50" "85°C" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Min Operating TempD1" "-40°C" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mount" "Surface Mount" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Number of Elements" "1" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Number of LEDs" "1" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Number of Pins" "2" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Number of Terminals" "2" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package Quantity" "1" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packaging" "Tape and Reel" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Power Dissipation" "52mW" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Power Rating" "52mW" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Radiation Hardening" "No" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "REACH SVHC" "No SVHC" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Reverse Voltage" "5V" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Shape" "Rectangular" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Test Current" "20mA" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Viewing Angle" "170°" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Wavelength" "626nm" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Width" "1.25mm" (pt -110 20) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "ESP1"
    (compRef "ESP32_DEV_BOARD")
    (originalName "ESP32_Dev_Board")
  )
  (compInst "J1"
    (compRef "QWIIC_TO_I2C")
    (originalName "Qwiic_to_I2C")
  )
  (compInst "J2"
    (compRef "QWIIC_TO_I2C")
    (originalName "Qwiic_to_I2C")
  )
  (compInst "J3"
    (compRef "QWIIC_TO_I2C")
    (originalName "Qwiic_to_I2C")
  )
  (compInst "R1"
    (compRef "RES-2")
    (originalName "RES-2")
    (patternName "RESC1609X50X30NL8T20")
    (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2DescA4" "Datasheet" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "DatasheetVersion" "06/2012" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "0.45 mm" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Length" "1.55 mm" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer" "Vishay Semiconductor" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Max Operating Temp50" "155 degC" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Min Operating TempD1" "-55 degC" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mount" "Surface Mount" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mounting Technology" "Surface Mount" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package Quantity" "5000" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "0603" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packaging" "Tape and Reel" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Pins" "2" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "REACH SVHC" "Unknown" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RoHSCompliant" "true" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Voltage Rating" "75 V" (pt -30 120) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "R2"
    (compRef "RES-2")
    (originalName "RES-2")
    (patternName "RESC1609X50X30NL8T20")
    (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2DescA4" "Datasheet" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "DatasheetVersion" "06/2012" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "0.45 mm" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Length" "1.55 mm" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer" "Vishay Semiconductor" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Max Operating Temp50" "155 degC" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Min Operating TempD1" "-55 degC" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mount" "Surface Mount" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mounting Technology" "Surface Mount" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package Quantity" "5000" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "0603" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packaging" "Tape and Reel" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Pins" "2" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "REACH SVHC" "Unknown" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RoHSCompliant" "true" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Voltage Rating" "75 V" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "R3"
    (compRef "RES-2")
    (originalName "RES-2")
    (patternName "RESC1609X50X30NL8T20")
    (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2DescA4" "Datasheet" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "DatasheetVersion" "06/2012" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "0.45 mm" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Length" "1.55 mm" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer" "Vishay Semiconductor" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Max Operating Temp50" "155 degC" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Min Operating TempD1" "-55 degC" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mount" "Surface Mount" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mounting Technology" "Surface Mount" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package Quantity" "5000" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "0603" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packaging" "Tape and Reel" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Pins" "2" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "REACH SVHC" "Unknown" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RoHSCompliant" "true" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Voltage Rating" "75 V" (pt -120 150) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "R4"
    (compRef "RES-2")
    (originalName "RES-2")
    (patternName "RESC1609X50X30NL8T20")
    (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2DescA4" "Datasheet" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "DatasheetVersion" "06/2012" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "0.45 mm" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Length" "1.55 mm" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer" "Vishay Semiconductor" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Max Operating Temp50" "155 degC" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Min Operating TempD1" "-55 degC" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mount" "Surface Mount" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mounting Technology" "Surface Mount" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package Quantity" "5000" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "0603" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packaging" "Tape and Reel" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Pins" "2" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "REACH SVHC" "Unknown" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RoHSCompliant" "true" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Voltage Rating" "75 V" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "R5"
    (compRef "RES-2")
    (originalName "RES-2")
    (patternName "RESC1609X50X30NL8T20")
    (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2DescA4" "Datasheet" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "DatasheetVersion" "06/2012" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Height" "0.45 mm" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Length" "1.55 mm" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Manufacturer" "Vishay Semiconductor" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Max Operating Temp50" "155 degC" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Min Operating TempD1" "-55 degC" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mount" "Surface Mount" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mounting Technology" "Surface Mount" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package Quantity" "5000" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "0603" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packaging" "Tape and Reel" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Pins" "2" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "REACH SVHC" "Unknown" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "RoHSCompliant" "true" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Voltage Rating" "75 V" (pt -30 320) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "P3V31"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V32"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V33"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V34"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V35"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V36"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V37"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "GND1"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND2"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND3"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND4"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND5"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "P3V38"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "GND6"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "P3V39"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "GND7"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "P3V310"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V311"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "P3V312"
    (compRef "3V3")
    (originalName "3V3")
  )
  (compInst "GND8"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND9"
    (compRef "GND")
    (originalName "GND")
  )
  (net "3V3"
    (node "C1" "2")
    (node "C2" "2")
    (node "CAM1" "1")
    (node "ESP1" "29")
    (node "ESP1" "30")
    (node "J1" "2")
    (node "J2" "2")
    (node "J3" "2")
    (node "R1" "1")
    (node "R2" "2")
    (node "R3" "1")
    (node "R4" "2")
    (node "R5" "2")
    (node "P3V31" "1")
    (node "P3V32" "1")
    (node "P3V33" "1")
    (node "P3V34" "1")
    (node "P3V35" "1")
    (node "P3V36" "1")
    (node "P3V37" "1")
    (node "P3V38" "1")
    (node "P3V39" "1")
    (node "P3V310" "1")
    (node "P3V311" "1")
    (node "P3V312" "1")
  )
  (net "GND"
    (node "C1" "1")
    (node "C2" "1")
    (node "CAM1" "2")
    (node "D1" "1")
    (node "ESP1" "27")
    (node "ESP1" "28")
    (node "J1" "1")
    (node "J2" "1")
    (node "J3" "1")
    (node "GND1" "1")
    (node "GND2" "1")
    (node "GND3" "1")
    (node "GND4" "1")
    (node "GND5" "1")
    (node "GND6" "1")
    (node "GND7" "1")
    (node "GND8" "1")
    (node "GND9" "1")
  )
  (net "NetCAM1_3"
    (node "CAM1" "3")
    (node "ESP1" "10")
    (node "J1" "3")
    (node "J2" "3")
    (node "J3" "3")
    (node "R2" "1")
    (node "R5" "1")
  )
  (net "NetCAM1_4"
    (node "CAM1" "4")
    (node "ESP1" "4")
    (node "J1" "4")
    (node "J2" "4")
    (node "J3" "4")
    (node "R3" "2")
    (node "R4" "1")
  )
  (net "NetD1_2"
    (node "D1" "2")
    (node "R1" "2")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader
    (workspaceSize 9500 7500)
    (gridDfns
      (grid "100mil")
    )
    (designInfo
      (fieldSet "(Default)"
        (fieldDef "Time" "")
        (fieldDef "Date" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Author" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Organization" "")
        (fieldDef "Address1" "")
        (fieldDef "Address2" "")
        (fieldDef "Address3" "")
        (fieldDef "Address4" "")
        (fieldDef "Title" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Revision" "")
        (fieldDef "Rule" "")
        (fieldDef "ImagePath" "")
        (fieldDef "ProjectName" "")
        (fieldDef "Application_BuildNumber" "")
      )
    )
    (refPointSize 100)
    (infoPointSize 100)
    (junctionSize 20)
    (refPointSizePrint 100)
    (infoPointSizePrint 100)
    (junctionSizePrint 20)
  )

  (sheet "ThermalCamV1" (sheetNum 1)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible True)
        (height 7500)
        (width 9500)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 4
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 4
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (wire (line (pt 7900 6300) (pt 7900 6000) (width 10) (netNameRef "NetD1_2") )
    )
    (wire (line (pt 1000 2800) (pt 1300 2800) (width 10) (netNameRef "NetCAM1_4") )
    )
    (wire (line (pt 1000 4400) (pt 1300 4400) (width 10) (netNameRef "NetCAM1_4") )
    )
    (wire (line (pt 1000 6000) (pt 1300 6000) (width 10) (netNameRef "NetCAM1_4") )
    )
    (wire (line (pt 8100 3200) (pt 7200 3200) (width 10) (netNameRef "NetCAM1_4") )
    )
    (wire (line (pt 7200 3200) (pt 6700 3200) (width 10) (netNameRef "NetCAM1_4") )
    )
    (wire (line (pt 7200 3300) (pt 7200 3200) (width 10) (netNameRef "NetCAM1_4") )
    )
    (wire (line (pt 1000 2600) (pt 1300 2600) (width 10) (netNameRef "NetCAM1_3") )
    )
    (wire (line (pt 1000 4200) (pt 1300 4200) (width 10) (netNameRef "NetCAM1_3") )
    )
    (wire (line (pt 1000 5800) (pt 1300 5800) (width 10) (netNameRef "NetCAM1_3") )
    )
    (wire (line (pt 8100 2900) (pt 7700 2900) (width 10) (netNameRef "NetCAM1_3") )
    )
    (wire (line (pt 7700 2900) (pt 6700 2900) (width 10) (netNameRef "NetCAM1_3") )
    )
    (wire (line (pt 7700 3300) (pt 7700 2900) (width 10) (netNameRef "NetCAM1_3") )
    )
    (wire (line (pt 4100 1800) (pt 4100 2000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 4100 2000) (pt 4200 2000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6000 5400) (pt 6000 5900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6700 2000) (pt 6800 2000) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6800 2000) (pt 6800 1800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6800 5400) (pt 6800 5900) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 1200 3000) (pt 1200 2400) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 1200 2400) (pt 1300 2400) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 1200 4600) (pt 1200 4000) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 1200 4000) (pt 1300 4000) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 1200 6200) (pt 1200 5600) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 1200 5600) (pt 1300 5600) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 3900 3700) (pt 3900 1900) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 3900 1900) (pt 4200 1900) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 4300 5500) (pt 4300 5200) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 4300 5200) (pt 4100 5200) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 4300 5200) (pt 4400 5200) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 6000 6700) (pt 6000 6200) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 6900 3700) (pt 6900 1900) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 6900 1900) (pt 6700 1900) (width 10) (netNameRef "3V3") )
    )
    (wire (line (pt 6800 6700) (pt 6800 6200) (width 10) (netNameRef "3V3") )
    )
    (port (pt 1000 2800) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_4") (isFlipped True)  )
    (port (pt 1000 4400) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_4") (isFlipped True)  )
    (port (pt 1000 6000) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_4") (isFlipped True)  )
    (port (pt 4800 5200) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_4")  )
    (port (pt 4900 6300) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_4")  )
    (port (pt 8100 3200) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_4")  )
    (port (pt 1000 2600) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_3") (isFlipped True)  )
    (port (pt 1000 4200) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_3") (isFlipped True)  )
    (port (pt 1000 5800) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_3") (isFlipped True)  )
    (port (pt 3700 5200) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_3") (isFlipped True)  )
    (port (pt 4900 6500) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_3")  )
    (port (pt 8100 2900) (portType NoAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetCAM1_3")  )
    (symbol (symbolRef "8706943c75ba83719d021d2fdc84c58_1_N") (refDesRef "D1") (partNum 1) (pt 7900 6000) (rotation 270.0)
      (attr "RefDes" "D1" (pt 230 -260) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Forward Voltage" "2.1V" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Shape" "Rectangular" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Number of Terminals" "2" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Wavelength" "626nm" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Lead Free" "Lead Free" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Min Operating TempD1" "-40°C" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Power Dissipation" "52mW" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Reverse Voltage" "5V" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package Quantity" "1" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Depth" "1.25mm" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Color" "Red" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Lens Style" "Diffused" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Number of Elements" "1" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mount" "Surface Mount" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Length" "2mm" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Dominant Wavelength" "626nm" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Lens Color" "White" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packaging" "Tape and Reel" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Case Code (Metric)" "2012" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Max Operating Temp50" "85°C" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Viewing Angle" "170°" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Test Current" "20mA" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Case Code (Imperial)" "0805" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Case/Package" "0805" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "0.8mm" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Number of LEDs" "1" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Illumination Color" "Red" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Width" "1.25mm" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Radiation Hardening" "No" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Power Rating" "52mW" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "REACH SVHC" "No SVHC" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Number of Pins" "2" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Luminous Intensity" "10mcd" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Lens Transparency" "Diffused" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Forward Current" "20mA" (pt -110 20) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Red LED" (pt 230 -360) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "RES-2_1_N") (refDesRef "R1") (partNum 1) (pt 7900 6600) (rotation 270.0)
      (attr "RefDes" "R1" (pt 30 -90) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Vishay Semiconductor" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package Quantity" "5000" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "DatasheetVersion" "06/2012" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Min Operating TempD1" "-55 degC" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mounting Technology" "Surface Mount" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "0.45 mm" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "REACH SVHC" "Unknown" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "0603" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packaging" "Tape and Reel" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage Rating" "75 V" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Max Operating Temp50" "155 degC" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mount" "Surface Mount" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2DescA4" "Datasheet" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Length" "1.55 mm" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Pins" "2" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "RoHSCompliant" "true" (pt -30 120) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "1kO 0603" (pt 30 -190) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "RES-2_1_N") (refDesRef "R2") (partNum 1) (pt 3800 5200)
      (attr "RefDes" "R2" (pt -10 30) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Vishay Semiconductor" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package Quantity" "5000" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "DatasheetVersion" "06/2012" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Min Operating TempD1" "-55 degC" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mounting Technology" "Surface Mount" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "0.45 mm" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "REACH SVHC" "Unknown" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "0603" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packaging" "Tape and Reel" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage Rating" "75 V" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Max Operating Temp50" "155 degC" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mount" "Surface Mount" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2DescA4" "Datasheet" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Length" "1.55 mm" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Pins" "2" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "RoHSCompliant" "true" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "2.2kO 0603" (pt -10 -130) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "RES-2_1_N") (refDesRef "R3") (partNum 1) (pt 4500 5200)
      (attr "RefDes" "R3" (pt -10 30) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Vishay Semiconductor" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package Quantity" "5000" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "DatasheetVersion" "06/2012" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Min Operating TempD1" "-55 degC" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mounting Technology" "Surface Mount" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "0.45 mm" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "REACH SVHC" "Unknown" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "0603" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packaging" "Tape and Reel" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage Rating" "75 V" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Max Operating Temp50" "155 degC" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mount" "Surface Mount" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2DescA4" "Datasheet" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Length" "1.55 mm" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Pins" "2" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "RoHSCompliant" "true" (pt -120 150) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "2.2kO 0603" (pt -10 -130) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "MLX90640_1_N") (refDesRef "CAM1") (partNum 1) (pt 4200 6400)
      (attr "RefDes" "CAM1" (pt -300 300) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "MLX90640" (pt -300 -500) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "ESP32_Dev_Board_1_N") (refDesRef "ESP1") (partNum 1) (pt 5500 2500)
      (attr "RefDes" "ESP1" (pt -1000 900) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ESP32 Dev Board" (pt -1000 -800) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Qwiic_to_I2C_1_N") (refDesRef "J1") (partNum 1) (pt 1600 5700)
      (attr "RefDes" "J1" (pt 0 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Qwiic to I2C" (pt 0 -500) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "CAP_1_N") (refDesRef "C1") (partNum 1) (pt 5900 6000) (rotation 90.0)
      (attr "RefDes" "C1" (pt 190 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Part Number" "C0603C105K3RACTU" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Kemet" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "0.1uF 25V 0603" (pt 190 -90) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "CAP_1_N") (refDesRef "C2") (partNum 1) (pt 6700 6000) (rotation 90.0)
      (attr "RefDes" "C2" (pt 190 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Part Number" "C0603C105K3RACTU" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Kemet" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "1uF 25V 0603" (pt 190 -90) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V31") (partNum 1) (pt 3900 3700) (rotation 90.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V32") (partNum 1) (pt 6900 3700) (rotation 90.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V33") (partNum 1) (pt 4300 5500) (rotation 90.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V34") (partNum 1) (pt 3600 6500) (rotation 180.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V35") (partNum 1) (pt 7900 6700) (rotation 90.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V36") (partNum 1) (pt 6000 6700) (rotation 90.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V37") (partNum 1) (pt 6800 6700) (rotation 90.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND1") (partNum 1) (pt 7900 5400) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND2") (partNum 1) (pt 6000 5400) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND3") (partNum 1) (pt 6800 5400) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND4") (partNum 1) (pt 3600 6300) (rotation 180.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND5") (partNum 1) (pt 1300 5400) (rotation 270.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V38") (partNum 1) (pt 1200 6200) (rotation 90.0) )
    (text  (pt 6100 900) "Thermal Camera Queue Detection System" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (text  (pt 8700 600) "V1" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (text  (pt 8400 300) "Li Zhifang" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (symbol (symbolRef "Qwiic_to_I2C_1_N") (refDesRef "J2") (partNum 1) (pt 1600 4100)
      (attr "RefDes" "J2" (pt 0 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Qwiic to I2C" (pt 0 -500) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND6") (partNum 1) (pt 1300 3800) (rotation 270.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V39") (partNum 1) (pt 1200 4600) (rotation 90.0) )
    (symbol (symbolRef "Qwiic_to_I2C_1_N") (refDesRef "J3") (partNum 1) (pt 1600 2500)
      (attr "RefDes" "J3" (pt 0 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Qwiic to I2C" (pt 0 -500) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND7") (partNum 1) (pt 1300 2200) (rotation 270.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V310") (partNum 1) (pt 1200 3000) (rotation 90.0) )
    (symbol (symbolRef "RES-2_1_N") (refDesRef "R5") (partNum 1) (pt 7700 3400) (rotation 90.0)
      (attr "RefDes" "R5" (pt 30 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Vishay Semiconductor" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package Quantity" "5000" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "DatasheetVersion" "06/2012" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Min Operating TempD1" "-55 degC" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mounting Technology" "Surface Mount" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "0.45 mm" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "REACH SVHC" "Unknown" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "0603" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packaging" "Tape and Reel" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage Rating" "75 V" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Max Operating Temp50" "155 degC" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mount" "Surface Mount" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2DescA4" "Datasheet" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Length" "1.55 mm" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Pins" "2" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "RoHSCompliant" "true" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "10kO 0603" (pt 30 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "RES-2_1_N") (refDesRef "R4") (partNum 1) (pt 7200 3400) (rotation 90.0)
      (attr "RefDes" "R4" (pt 30 110) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Manufacturer" "Vishay Semiconductor" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package Quantity" "5000" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "DatasheetVersion" "06/2012" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Min Operating TempD1" "-55 degC" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1URL" "http://www.vishay.com/" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mounting Technology" "Surface Mount" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Height" "0.45 mm" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1DescBC" "Manufacturer URL" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "REACH SVHC" "Unknown" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "0603" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packaging" "Tape and Reel" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Voltage Rating" "75 V" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Max Operating Temp50" "155 degC" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mount" "Surface Mount" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2DescA4" "Datasheet" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "2-Pin Surface Mount Device, Body 1.575 x 0.85 mm" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Length" "1.55 mm" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2URL" "http://www.vishay.com/docs/20035/dcrcwe3.pdf" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Pins" "2" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "RoHSCompliant" "true" (pt -30 320) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "10kO 0603" (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V311") (partNum 1) (pt 7200 3700) (rotation 90.0) )
    (symbol (symbolRef "3V3_1_N") (refDesRef "P3V312") (partNum 1) (pt 7700 3700) (rotation 90.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND8") (partNum 1) (pt 6800 1800) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND9") (partNum 1) (pt 4100 1800) (rotation 270.0) )
    (line (pt 4197 3303) (pt 4203 3297) (width 5) )
    (line (pt 4197 3297) (pt 4203 3303) (width 5) )
    (line (pt 4197 3203) (pt 4203 3197) (width 5) )
    (line (pt 4197 3197) (pt 4203 3203) (width 5) )
    (line (pt 4197 3103) (pt 4203 3097) (width 5) )
    (line (pt 4197 3097) (pt 4203 3103) (width 5) )
    (line (pt 4197 3003) (pt 4203 2997) (width 5) )
    (line (pt 4197 2997) (pt 4203 3003) (width 5) )
    (line (pt 4197 2903) (pt 4203 2897) (width 5) )
    (line (pt 4197 2897) (pt 4203 2903) (width 5) )
    (line (pt 4197 2803) (pt 4203 2797) (width 5) )
    (line (pt 4197 2797) (pt 4203 2803) (width 5) )
    (line (pt 4197 2703) (pt 4203 2697) (width 5) )
    (line (pt 4197 2697) (pt 4203 2703) (width 5) )
    (line (pt 4197 2603) (pt 4203 2597) (width 5) )
    (line (pt 4197 2597) (pt 4203 2603) (width 5) )
    (line (pt 4197 2503) (pt 4203 2497) (width 5) )
    (line (pt 4197 2497) (pt 4203 2503) (width 5) )
    (line (pt 4197 2403) (pt 4203 2397) (width 5) )
    (line (pt 4197 2397) (pt 4203 2403) (width 5) )
    (line (pt 4197 2303) (pt 4203 2297) (width 5) )
    (line (pt 4197 2297) (pt 4203 2303) (width 5) )
    (line (pt 4197 2203) (pt 4203 2197) (width 5) )
    (line (pt 4197 2197) (pt 4203 2203) (width 5) )
    (line (pt 4197 2103) (pt 4203 2097) (width 5) )
    (line (pt 4197 2097) (pt 4203 2103) (width 5) )
    (line (pt 6697 3303) (pt 6703 3297) (width 5) )
    (line (pt 6697 3297) (pt 6703 3303) (width 5) )
    (line (pt 6697 3103) (pt 6703 3097) (width 5) )
    (line (pt 6697 3097) (pt 6703 3103) (width 5) )
    (line (pt 6697 2803) (pt 6703 2797) (width 5) )
    (line (pt 6697 2797) (pt 6703 2803) (width 5) )
    (line (pt 6697 2703) (pt 6703 2697) (width 5) )
    (line (pt 6697 2697) (pt 6703 2703) (width 5) )
    (line (pt 6697 2603) (pt 6703 2597) (width 5) )
    (line (pt 6697 2597) (pt 6703 2603) (width 5) )
    (line (pt 6697 2503) (pt 6703 2497) (width 5) )
    (line (pt 6697 2497) (pt 6703 2503) (width 5) )
    (line (pt 6697 2303) (pt 6703 2297) (width 5) )
    (line (pt 6697 2297) (pt 6703 2303) (width 5) )
    (line (pt 6697 2403) (pt 6703 2397) (width 5) )
    (line (pt 6697 2397) (pt 6703 2403) (width 5) )
    (line (pt 6697 2103) (pt 6703 2097) (width 5) )
    (line (pt 6697 2097) (pt 6703 2103) (width 5) )
    (line (pt 6697 2203) (pt 6703 2197) (width 5) )
    (line (pt 6697 2197) (pt 6703 2203) (width 5) )
    (line (pt 6697 3003) (pt 6703 2997) (width 5) )
    (line (pt 6697 2997) (pt 6703 3003) (width 5) )
    (text  (pt 500 7000) "Qwiic/I2C Connections" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (text  (pt 3000 7000) "MLX90640" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (text  (pt 3000 4400) "ESP32-DevKitC" (textStyleRef "10pTIMESNEWROMANBOLD") (justify UpperLeft) (extent 0.0 0.0) )
    (line (pt 2600 7300) (pt 2600 200) (width 15) )
    (line (pt 2600 4700) (pt 9300 4700) (width 15) )
  )
  (schematicPrintSettings
    (sheetList
      (sheetRef 2)
    )
  )
  (programState
    (gridState
      (currentAbsGrid "100mil")
      (currentRelGrid "100mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "(Default)")
  )
)
