//
// Created by Zhifang L on 04/03/2026.
//

#ifndef MINI_IOT_THERMAL_SENSING_USER_CONFIG_H
#define MINI_IOT_THERMAL_SENSING_USER_CONFIG_H

//NEED TO ADD STUFF

#endif //MINI_IOT_THERMAL_SENSING_USER_CONFIG_H